services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile.jenkins
    privileged: true
    user: root
    ports:
    - 8081:8080 # jenkins runs on port 8080 but 8080 is used by gradle so 
    - 50000:50000
    container_name: jenkins
    volumes:
    - /workspaces/ENSF-400-Term-Project/jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
