name: Build and Push Docker Image

on:
  push:
    branches:
      - main  #Trigger action when pushing to main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest  #Specifies the GitHub Actions runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  #Checks out the code from the repository

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  #Use GitHub secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  #Use GitHub secret for Docker Hub password

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # This sets up Docker Buildx for multi-platform builds

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .               #Current directory is build context
          file: ./Dockerfile       #Path to Dockerfile
          push: true               #Push the image to Docker after building
          tags: |
            rustyglint/my_app:${{ github.sha }}  # Use the commit SHA as a unique tag
            rustyglint/my_app:latest             # Use the 'latest' tag
